name: hello-bff

service:
  type: ClusterIP
  port: 80

serviceAccount:
  create: false
  annotations: {}
  name: ""

repository:
  owner: heliandro
  name: hello-bff
  tag: v0.6.10

image:
  pullPolicy: Always

container:
  port: 3000

env:
  PORT: 3000
  APP_PREFIX: hello
  APP_TIER: bff
  LOCALE: pt-BR
  CACHE_PREFIX: hello
  LOG_LABEL: hello-bff
  TRACE_EXPORT_URL: http://jaeagertracing-collector.todo
  ENVIRONMENT: dev

replicaCount: 2

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80