name: hello-bff
service:
  type: ClusterIP
  port: 80
image:
  repository: heliandro
  name: hello-bff
  pullPolicy: IfNotPresent
  version: 0.1.0
container:
  port: 3000
env: [
  { NODE_ENV: "development" },
  { PORT: 3000 }
]
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
replicaCount: 2
autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70